version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
      - APP_ENV=dev
      - JWT_SECRET=your_jwt_secret
      - LOG_LEVEL=debug
      # Database config
      - DB_HOST=db # Use service name 'db' as host
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_NAME=api
      - DB_SYNC=true
      # Redis config
      - REDIS_HOST=redis # Use service name 'redis' as host
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      # Mail config
      - MAIL_FROM=noreply@example.com
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MAIL_AUTH_USER=
      - MAIL_AUTH_PASS=
    depends_on:
      - db
      - redis
      - mailhog

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: api
      # POSTGRES_USER: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    ports: ["1025:1025", "8025:8025"]
