import { MigrationInterface, QueryRunner } from "typeorm";

export class OptimizeBankAccount1744899688336 implements MigrationInterface {
    name = 'OptimizeBankAccount1744899688336'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."payout_destinations_type_enum" AS ENUM('internal', 'wire', 'nip', 'stablecoin')`);
        await queryRunner.query(`CREATE TABLE "payout_destinations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "source_type" character varying NOT NULL, "type" "public"."payout_destinations_type_enum" NOT NULL, "destination_type" character varying, "account_type" character varying, "wire_type" character varying, "bank_code" character varying, "bank_name" character varying, "account_number" character varying, "routing_number" character varying, "routing_type" character varying, "account_name" character varying, "beneficiary_name" character varying, "beneficiary_address" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "wallet_id" character varying, CONSTRAINT "PK_924d833e18bd45e8ed4609a6104" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payouts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" character varying NOT NULL, "amount" integer NOT NULL, "description" character varying NOT NULL, "destination_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_62abf8ed64ce0beca1989c4bec" UNIQUE ("destination_id"), CONSTRAINT "PK_76855dc4f0a6c18c72eea302e87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "depositId"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "transactionId"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "accountId"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "balanceBefore"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "balanceAfter"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "linkedTransactionId"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "payoutId"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "walletAccountId"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "walletCurrency"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "walletBalance"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "walletKind"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "walletStatus"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "depositObjectType"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "depositAccountType"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "depositType"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "depositConfirmations"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "depositAmountSource"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "depositAmountSettled"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "depositFee"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "depositSettlementType"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "depositSettlementRate"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "depositCurrencySource"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "depositNetwork"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "depositChainHash"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "transactionCreatedAt"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "transactionUpdatedAt"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "depositCreatedAt"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "depositUpdatedAt"`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" ADD "balance" integer`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "deposit_id" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "transaction_id" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "account_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "account_type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "object_type" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "organisation_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "balance_before" numeric(20,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "balance_after" numeric(20,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "currency_settlement" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "custom_reference" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "linked_transaction_id" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "payout_id" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "charge_id" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "conversion_id" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "card_id" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_account_id" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_account_name" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_account_number" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_name" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_code" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_type" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_routing_number" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_swift_code" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_iban" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_balance" numeric(20,2)`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_currency" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_currency_settlement" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_credit_pending" numeric(20,2)`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_debit_pending" numeric(20,2)`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_status" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_holder_id" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_holder_type" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_address_line1" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_address_line2" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_address_city" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_address_state" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_address_country" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_address_postal_code" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "beneficiary_address_line1" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "beneficiary_address_line2" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "beneficiary_address_city" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "beneficiary_address_state" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "beneficiary_address_country" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "beneficiary_address_postal_code" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "wallet_account_id" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "wallet_currency" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "wallet_balance" numeric(20,2)`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "wallet_kind" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "wallet_status" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "deposit_object_type" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "deposit_account_type" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "deposit_type" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "deposit_confirmations" integer`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "deposit_amount_source" numeric(20,2)`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "deposit_amount_settled" numeric(20,2)`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "deposit_fee" numeric(20,2)`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "deposit_settlement_type" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "deposit_settlement_rate" numeric(10,6)`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "deposit_currency_source" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "payer_account_name" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "payer_account_number" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "payer_bank_code" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "payer_bank_name" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "payer_routing_number" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "payer_routing_type" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "payer_routing_rail" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "payer_trace_number" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "payer_session_id" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "payer_network" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "payer_chain_hash" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "transaction_created_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "transaction_updated_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "deposit_created_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "deposit_updated_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_created_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "bank_updated_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payout_destinations" ADD CONSTRAINT "FK_851a7394295827f48cf8b3f31d3" FOREIGN KEY ("wallet_id") REFERENCES "wallet_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payout_destinations" ADD CONSTRAINT "FK_2bdea89c6149bb6521e9f8ca733" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD CONSTRAINT "FK_62abf8ed64ce0beca1989c4beca" FOREIGN KEY ("destination_id") REFERENCES "payout_destinations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "payouts" DROP CONSTRAINT "FK_62abf8ed64ce0beca1989c4beca"`);
        await queryRunner.query(`ALTER TABLE "payout_destinations" DROP CONSTRAINT "FK_2bdea89c6149bb6521e9f8ca733"`);
        await queryRunner.query(`ALTER TABLE "payout_destinations" DROP CONSTRAINT "FK_851a7394295827f48cf8b3f31d3"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_updated_at"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_created_at"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "deposit_updated_at"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "deposit_created_at"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "transaction_updated_at"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "transaction_created_at"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "payer_chain_hash"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "payer_network"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "payer_session_id"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "payer_trace_number"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "payer_routing_rail"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "payer_routing_type"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "payer_routing_number"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "payer_bank_name"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "payer_bank_code"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "payer_account_number"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "payer_account_name"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "deposit_currency_source"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "deposit_settlement_rate"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "deposit_settlement_type"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "deposit_fee"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "deposit_amount_settled"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "deposit_amount_source"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "deposit_confirmations"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "deposit_type"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "deposit_account_type"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "deposit_object_type"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "wallet_status"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "wallet_kind"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "wallet_balance"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "wallet_currency"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "wallet_account_id"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "beneficiary_address_postal_code"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "beneficiary_address_country"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "beneficiary_address_state"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "beneficiary_address_city"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "beneficiary_address_line2"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "beneficiary_address_line1"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_address_postal_code"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_address_country"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_address_state"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_address_city"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_address_line2"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_address_line1"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_holder_type"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_holder_id"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_status"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_debit_pending"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_credit_pending"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_currency_settlement"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_currency"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_balance"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_iban"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_swift_code"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_routing_number"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_type"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_code"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_name"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_account_number"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_account_name"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "bank_account_id"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "card_id"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "conversion_id"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "charge_id"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "payout_id"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "linked_transaction_id"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "custom_reference"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "currency_settlement"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "balance_after"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "balance_before"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "organisation_id"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "object_type"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "account_type"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "account_id"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "transaction_id"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP COLUMN "deposit_id"`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" DROP COLUMN "balance"`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "depositUpdatedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "depositCreatedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "transactionUpdatedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "transactionCreatedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "depositChainHash" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "depositNetwork" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "depositCurrencySource" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "depositSettlementRate" numeric(10,6)`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "depositSettlementType" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "depositFee" numeric(20,2)`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "depositAmountSettled" numeric(20,2)`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "depositAmountSource" numeric(20,2)`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "depositConfirmations" integer`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "depositType" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "depositAccountType" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "depositObjectType" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "walletStatus" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "walletKind" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "walletBalance" numeric(20,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "walletCurrency" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "walletAccountId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "payoutId" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "linkedTransactionId" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "balanceAfter" numeric(20,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "balanceBefore" numeric(20,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "accountId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "transactionId" character varying`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD "depositId" character varying`);
        await queryRunner.query(`DROP TABLE "payouts"`);
        await queryRunner.query(`DROP TABLE "payout_destinations"`);
        await queryRunner.query(`DROP TYPE "public"."payout_destinations_type_enum"`);
    }

}
