import { User } from '../user.entity'

export const mockUserEntity: User = {
  id: 'adfs9-3j2k-3j2k-3j2k',
  email: 'email',
  lastName: 'lName',
  firstName: 'fName',
  otherName: 'null',
  token: 'token',
  passwordHash: 'password',
  businessName: 'businessName',
  emailVerified: false,
  phone: 'null',
  dob: new Date('dateString'),
  idLevel: 'primary',
  idType: 'null',
  idNumber: 'null',
  idCountry: 'null',
  bankIdNumber: 'null',
  kycLevel: 'basic',
  address: {
    line1: 'line1',
    line2: 'line2',
    city: 'city',
    state: 'state',
    country: 'country',
    postalCode: 'postalCode',
  },
  backgroundInformation: {
    occupation: 'Software Engineer',
    primaryPurpose: '',
    sourceOfFunds: '',
    expectedMonthly: '',
    employmentStatus: '',
  },
  documents: [],
  dateCreated: new Date(),
  dateUpdated: new Date(),
  kycStatus: 'verified',
  kycResponse: {},
  businesses: [],
  proofOfAddress: 'sss',
  kycStep: '',
  partnerReferences: [],
  bankAccounts: [],
}
