import { UserEntity } from '../user.entity';

export const mockUserEntity: UserEntity = {
  id: 'adfs9-3j2k-3j2k-3j2k',
  email: 'email',
  lastName: 'lName',
  firstName: 'fName',
  otherName: 'null',
  token: 'token',
  passwordHash: 'password',
  businessName: 'businessName',
  emailVerified: false,
  phone: 'null',
  dob: new Date('dateString'),
  idLevel: 'primary',
  idType: 'null',
  idNumber: 'null',
  idCountry: 'null',
  bankIdNumber: 'null',
  kycLevel: 'basic',
  address: {},
  background_information: {},
  documents: [],
  dateCreated: new Date(),
  dateUpdated: new Date(),
  kyc_status: 'verified',
  kyc_response: null,
  businesses: [],
  proof_of_address: 'sss',
  kyc_step: '',
  partner_references: [],
  bankAccounts: []
};
